"""Ontology snapshot / restore / reset (operator spec item 1).

Each ontology snapshot bundles the project's learnable state:
  config/constitution.json         (with all accumulated legislation)
  config/convention_registry.json
  config/institution_registry.json
  config/verification_memory.json
  config/citation_convention.json
  config/speech_acts_taxonomy.json
  config/search_strategy_learnings.json
  config/discovered_apis.json
  config/document_dates.json
  config/review_scope.json
  reference/LINGUISTIC_IDENTITY.md
  reference/situational_awareness.md
  prompts/project_rules.md

reset_ontology() strips back to genesis defaults:
  - constitution -> 7 seed laws only (no precedents/TFLs/amendments)
  - all spawned configs deleted
  - reference/ cleared
  - output/ cleared
  - prompts/project_rules.md reverted to clean template
  - input/operational/ emptied (per spec: this is a runtime artifact)
  - input/context/ and input/conventions/ preserved (operator-supplied inputs)
"""

from __future__ import annotations

import json
import shutil
from datetime import datetime, timezone
from pathlib import Path


_LEARNABLE_CONFIG = [
    "constitution.json", "convention_registry.json", "institution_registry.json",
    "verification_memory.json", "citation_convention.json", "speech_acts_taxonomy.json",
    "search_strategy_learnings.json", "discovered_apis.json",
    "document_dates.json", "review_scope.json",
]
_LEARNABLE_REFERENCE = ["LINGUISTIC_IDENTITY.md", "situational_awareness.md"]
_LEARNABLE_PROMPTS = ["project_rules.md"]
# Embedding store (genesis Part XXI). Lives at output/audit/embedding_store.pkl;
# snapshotted into ontologies/<name>/output/audit/embedding_store.pkl.
_LEARNABLE_AUDIT = ["embedding_store.pkl"]


_GENESIS_CONSTITUTION = {
    "version": "1.0.0",
    "description": "Reset to genesis defaults (7 seed laws only).",
    "seed_laws": [
        {"id": "LAW-0", "title": "Operator sovereignty", "priority": 0, "immutable": True,
         "text": "The operator is the sole source of constitutional authority. No agent, task force, supervisor, or orchestrator may create, amend, or repeal a law without operator approval. The constitution governs all agent behavior. Silence in the constitution means escalate — never assume permission. Every operator decision on an escalation is recorded as legislation (precedent, task force law, or amendment) for future runs.",
         "outranked_by": ["LAW-IV"]},
        {"id": "LAW-I", "title": "Do no harm to the source", "priority": 1, "immutable": True,
         "text": "No agent may alter, fabricate, or suppress information from source documents. An agent may flag, annotate, footnote, and warn — but the source record is sacred. When source content conflicts with external evidence, both are preserved and the operator decides. No agent may resolve a factual conflict by choosing one version over another."},
        {"id": "LAW-II", "title": "Know your bounds", "priority": 2, "immutable": True,
         "text": "Each agent has a fixed capability set defined in the agent registry. An agent may request another agent's service but may not perform another agent's function. An agent that detects itself reasoning outside its defined scope must stop and yield to the appropriate agent. The capability boundary is the agent's identity — crossing it is not initiative, it is malfunction."},
        {"id": "LAW-III", "title": "No self-audit", "priority": 3, "immutable": True,
         "text": "No model may verify, fact-check, or audit output that was generated by the same model family. Claude-generated content is audited by GPT or local models. GPT-generated content is audited by Claude or local models. Local model output is audited by cloud models. The audit trail must show which model produced and which model verified every output segment."},
        {"id": "LAW-IV", "title": "Protect what is private", "priority": 4, "immutable": True,
         "text": "Sensitive content — PII, classified material, institutional secrets, content marked for redaction — must be processed exclusively by offline agents running on local hardware. No sensitive content may traverse a network, enter an API call, or leave the operator's machine. This law cannot be overridden by any subsequent legislation, precedent, amendment, or operator instruction. It outranks LAW-0 for this specific scope. A single leak is irreversible.",
         "outranks": ["LAW-0"]},
        {"id": "LAW-V", "title": "Remember before you act", "priority": 5, "immutable": True,
         "text": "Before executing any search, verification, or computation, an agent must check in order: (a) the constitution for governing law, (b) the precedent registry for prior rulings, (c) the verification memory for cached results, (d) the run objectives for alignment. Act on the first match found. Only when all four are silent may the agent proceed with a novel action — and that action's outcome must be recorded for future consultation.",
         "check_order": ["constitution", "precedents", "verification_memory", "run_objectives"]},
        {"id": "LAW-VI", "title": "Structure is earned, not assumed", "priority": 6, "immutable": True,
         "text": "All organizational structure below the Top Orchestrator emerges from identified work. Agents form task forces by drafting charters. Charters require constitutional approval from the Top Orchestrator, which checks against existing legislation. If the constitution is silent on the proposed pattern, the Top Orchestrator escalates to the operator. Approved charters become task force laws upon dissolution. No structure persists beyond its purpose — a task force with no remaining work must dissolve. No agent may invent work to justify its existence."},
    ],
    "task_force_laws": [], "precedents": [], "amendments": [],
}


_CLEAN_PROJECT_RULES = (
    "# Project rules\n\n"
    "This file holds project-specific rules layered over the constitution. The seed laws "
    "(LAW-0 through LAW-VI in `config/constitution.json`) outrank everything written here. "
    "These rules are domain-agnostic placeholders; the adaptive-spawn step appends "
    "project-specific rules learned from the first run.\n\n"
    "## Manual rules (operator-set)\n\n"
    "_(None yet. Add rules here that should apply to every run of this project. "
    "Use the same prose voice as the seed laws — short, declarative, no ambiguity. "
    "Each rule should cite the operator decision or DELTA that produced it.)_\n\n"
    "## DELTAs flushed by adaptive spawn\n\n"
    "_(Populated automatically when the audit synthesis proposes a project-scoped DELTA "
    "and the operator approves. Do not edit by hand.)_\n"
)


def _now(): return datetime.now(timezone.utc).isoformat()


def list_ontologies(project_root: Path) -> list[dict]:
    base = project_root / "ontologies"
    if not base.exists():
        return []
    out = []
    for sub in sorted(base.iterdir()):
        if not sub.is_dir():
            continue
        meta_path = sub / "_ontology.json"
        meta = {}
        if meta_path.exists():
            try: meta = json.loads(meta_path.read_text(encoding="utf-8"))
            except json.JSONDecodeError: meta = {}
        out.append({"name": sub.name, "path": str(sub), **meta})
    return out


def save_ontology(project_root: Path, name: str, *, overwrite: bool = False) -> Path:
    target = project_root / "ontologies" / name
    if target.exists() and not overwrite:
        raise FileExistsError(f"ontology {name!r} already exists; pass overwrite=True to replace")
    if target.exists():
        shutil.rmtree(target)
    (target / "config").mkdir(parents=True, exist_ok=True)
    (target / "reference").mkdir(parents=True, exist_ok=True)
    (target / "prompts").mkdir(parents=True, exist_ok=True)
    (target / "output" / "audit").mkdir(parents=True, exist_ok=True)
    copied = []
    for fn in _LEARNABLE_CONFIG:
        src = project_root / "config" / fn
        if src.exists():
            shutil.copy2(src, target / "config" / fn); copied.append(f"config/{fn}")
    for fn in _LEARNABLE_REFERENCE:
        src = project_root / "reference" / fn
        if src.exists():
            shutil.copy2(src, target / "reference" / fn); copied.append(f"reference/{fn}")
    for fn in _LEARNABLE_PROMPTS:
        src = project_root / "prompts" / fn
        if src.exists():
            shutil.copy2(src, target / "prompts" / fn); copied.append(f"prompts/{fn}")
    for fn in _LEARNABLE_AUDIT:
        src = project_root / "output" / "audit" / fn
        if src.exists():
            shutil.copy2(src, target / "output" / "audit" / fn)
            copied.append(f"output/audit/{fn}")
    meta = {"name": name, "saved_at": _now(), "files": copied}
    (target / "_ontology.json").write_text(json.dumps(meta, indent=2, ensure_ascii=False),
                                            encoding="utf-8")
    return target


def load_ontology(project_root: Path, name: str) -> dict:
    target = project_root / "ontologies" / name
    if not target.is_dir():
        raise FileNotFoundError(f"ontology {name!r} not found")
    summary = {"name": name, "restored": [], "cleared": []}
    for fn in _LEARNABLE_CONFIG:
        src = target / "config" / fn
        if src.exists():
            dst = project_root / "config" / fn
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst); summary["restored"].append(f"config/{fn}")
    for fn in _LEARNABLE_REFERENCE:
        src = target / "reference" / fn
        if src.exists():
            dst = project_root / "reference" / fn
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst); summary["restored"].append(f"reference/{fn}")
    for fn in _LEARNABLE_PROMPTS:
        src = target / "prompts" / fn
        if src.exists():
            dst = project_root / "prompts" / fn
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst); summary["restored"].append(f"prompts/{fn}")
    # Clear output and tier-1 cache. Preserve tier 2/3 since they came from
    # the ontology. The embedding store is restored AFTER clearing output/audit
    # so the freshly-restored pickle survives the wipe.
    for sub in ("deliverables", "audit", "logs"):
        path = project_root / "output" / sub
        if path.exists():
            for f in path.glob("*"):
                if f.is_file(): f.unlink()
                elif f.is_dir(): shutil.rmtree(f)
            summary["cleared"].append(f"output/{sub}/*")
    for fn in _LEARNABLE_AUDIT:
        src = target / "output" / "audit" / fn
        if src.exists():
            dst = project_root / "output" / "audit" / fn
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)
            summary["restored"].append(f"output/audit/{fn}")
    return summary


def reset_ontology(project_root: Path) -> dict:
    """Strip all learned state. Seeded files revert to genesis defaults."""
    summary = {"deleted": [], "reset": []}
    # Spawned/learnable configs (delete entirely, except constitution which we rewrite).
    for fn in _LEARNABLE_CONFIG:
        path = project_root / "config" / fn
        if path.exists():
            path.unlink(); summary["deleted"].append(f"config/{fn}")
    # Rewrite constitution to seed defaults.
    constitution_path = project_root / "config" / "constitution.json"
    constitution_path.parent.mkdir(parents=True, exist_ok=True)
    constitution_path.write_text(
        json.dumps(_GENESIS_CONSTITUTION, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    summary["reset"].append("config/constitution.json")
    # Clear reference/
    ref_dir = project_root / "reference"
    if ref_dir.exists():
        for f in ref_dir.glob("*"):
            if f.is_file(): f.unlink(); summary["deleted"].append(f"reference/{f.name}")
    # Reset prompts/project_rules.md
    rules_path = project_root / "prompts" / "project_rules.md"
    rules_path.parent.mkdir(parents=True, exist_ok=True)
    rules_path.write_text(_CLEAN_PROJECT_RULES, encoding="utf-8")
    summary["reset"].append("prompts/project_rules.md")
    # Clear output/
    out_dir = project_root / "output"
    if out_dir.exists():
        for sub in ("deliverables", "audit", "logs"):
            path = out_dir / sub
            if path.exists():
                for f in path.glob("*"):
                    if f.is_file(): f.unlink()
                    elif f.is_dir(): shutil.rmtree(f)
                summary["deleted"].append(f"output/{sub}/*")
    # Empty input/operational/ (runtime artifact per spec)
    op_dir = project_root / "input" / "operational"
    if op_dir.exists():
        for f in op_dir.glob("*"):
            if f.is_file(): f.unlink()
        summary["deleted"].append("input/operational/*")
    return summary
